logging:
  level:
    root: INFO
  file:
    path: logs_acb
  config: classpath:logback-spring.xml
  
server:
  servlet:
    context-path: /logging
  port: 8081
  
app:
  api:
    logstash:
      host: localhost
      port: 5000